# Generated by Django 4.1.2 on 2022-12-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('dob', models.DateTimeField()),
                ('dept_name', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
            ],
        ),
    ]
